### ISSUE TITLE
Unable to set bands on Dish 5G MR6400

### ISSUE THREAD

**Issue by r00tedu** [0xBAADF0OD/netgear_mr6400#4]
Can you give a band set for a Dish 5G MR6400?

https://github.com/0xBAADF0OD/netgear_mr6400/tree/main/netgear-AT-commands#set-some-bands

ATI
Manufacturer: Netgear, Incorporated
Model: MR6400
Revision: NTGX65_10.01.41.02 r8801 ntgrbc-fwbuild7 2022/06/22 21:21:25
IMEI: 01623800001xxxx
IMEI SV: 5
FSN: 71Y125WE0xxxx
+GCAP: +CGSM

AT!BAND?
AT!BAND?
Index, Name,         GW_Mask          LTE_1-64         LTE_65-128       NR5G_1-64        NR5G_65-128      NR5G_257-320
00, All,             0000000000000000 0000A1003300385F 0000000000000042 0000810031002812 0000000000001042 0000000000000000

OK
AT!BAND=?
AT!BAND=?
Index, Name,         GW_Mask          LTE_1-64         LTE_65-128       NR5G_1-64        NR5G_65-128      NR5G_257-320
00, All,             0000000000000000 0000A1003300385F 0000000000000042 0000810031002812 0000000000001042 0000000000000000

                                      0000800000000000 - LTE B48    
                                      0000200000000000 - LTE B46    
                                      0000010000000000 - LTE B41    
                                      0000008000000000 - LTE B40    
                                      0000000020000000 - LTE B30    
                                      0000000010000000 - LTE B29    
                                      0000000002000000 - LTE B26    
                                      0000000001000000 - LTE B25    
                                      0000000000002000 - LTE B14    
                                      0000000000001000 - LTE B13    
                                      0000000000000800 - LTE B12    
                                      0000000000000040 - LTE B7     
                                      0000000000000010 - LTE B5     
                                      0000000000000008 - LTE B4     
                                      0000000000000004 - LTE B3     
                                      0000000000000002 - LTE B2     
                                      0000000000000001 - LTE B1     
                                                       0000000000000040 - LTE B71    
                                                       0000000000000002 - LTE B66    
                                                                        0000800000000000 - NR5G N48    
                                                                        0000010000000000 - NR5G N41    
                                                                        0000000020000000 - NR5G N30    
                                                                        0000000010000000 - NR5G N29    
                                                                        0000000001000000 - NR5G N25    
                                                                        0000000000002000 - NR5G N14    
                                                                        0000000000000800 - NR5G N12    
                                                                        0000000000000010 - NR5G N5     
                                                                        0000000000000002 - NR5G N2     
                                                                                         0000000000001000 - NR5G N77    
                                                                                         0000000000000040 - NR5G N71    
                                                                                         0000000000000002 - NR5G N66    
                                                                                                          0000000000000008 - NR5G N260   

OK

OK
AT!BAND=02,"TMO HIGH B2/4/66 n41/77",0,1000300000A,2,10001000000,1002,0
AT!BAND=02,"TMO HIGH B2/4/66 n41/77",0,1000300000A,2,10001000000,1002,0
ERROR
AT!BAND=03,"TMO NRSA n41/71/77",0,0,0,0000010001000000,1042,0
AT!BAND=03,"TMO NRSA n41/71/77",0,0,0,0000010001000000,1042,0
ERROR
AT!BAND=04,"VZW NRNSA B2/4/5/13/66 n2/5/66/77",0,101A,2,12,1002,0
AT!BAND=04,"VZW NRNSA B2/4/5/13/66 n2/5/66/77",0,101A,2,12,1002,0
ERROR

**Comment by 0xBAADF0OD** [comment]
So, it turns out that this is a "customized modem" and custom bands set on this device doesn't actually do anything. The MR6400 already prioritize DISH bands since it's a DISH device.

**Comment by W1lli0m** [comment]
not every band combination can be done with FW limitations, you can try to open all LTE bands along with specific nr5g bands, this might work
